# Generated by Django 6.1.1 on 2026-10-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
