# Generated by Django 6.1.1 on 2026-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
